[package]
name = "what-bin-is-it"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fantoccini = "0.19.3"
tokio = { version = "1.29.1", features = ["full"] }
